[package]
name = "DynamicNftGame"
version = "1.0.0"

[addresses]
GameAddr = "0xcafe"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
