[package]
name = "SoulboundToken"
version = "1.0.0"

[addresses]
0xcafe = "0xcafe"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", type = "internal", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
